package telerik

const (
	ACE_MODE_ABAP AceMode = iota + 1
	ACE_MODE_ABC
	ACE_MODE_ACTIONSCRIPT
	ACE_MODE_ADA
	ACE_MODE_APACHE_CONF
	ACE_MODE_ASCIIDOC
	ACE_MODE_ASSEMBLY_X86
	ACE_MODE_AUTOHOTKEY
	ACE_MODE_BATCHFILE
	ACE_MODE_BRO
	ACE_MODE_C_AND_C_PLUS_PLUS
	ACE_MODE_C9SEARCH
	ACE_MODE_CIRRU
	ACE_MODE_CLOJURE
	ACE_MODE_COBOL
	ACE_MODE_COFFEESCRIPT
	ACE_MODE_COLDFUSION
	ACE_MODE_C_SHARP
	ACE_MODE_CSOUND_DOCUMENT
	ACE_MODE_CSOUND
	ACE_MODE_CSOUND_SCORE
	ACE_MODE_CSS
	ACE_MODE_CURLY
	ACE_MODE_D
	ACE_MODE_DART
	ACE_MODE_DIFF
	ACE_MODE_DOCKERFILE
	ACE_MODE_DOT
	ACE_MODE_DROOLS
	ACE_MODE_EDIFACT
	ACE_MODE_EIFFEL
	ACE_MODE_EJS
	ACE_MODE_ELIXIR
	ACE_MODE_ELM
	ACE_MODE_ERLANG
	ACE_MODE_FORTH
	ACE_MODE_FORTRAN
	ACE_MODE_FREEMARKER
	ACE_MODE_GCODE
	ACE_MODE_GHERKIN
	ACE_MODE_GITIGNORE
	ACE_MODE_GLSL
	ACE_MODE_GOBSTONES
	ACE_MODE_GO
	ACE_MODE_GRAPHQLSCHEMA
	ACE_MODE_GROOVY
	ACE_MODE_HAML
	ACE_MODE_HANDLEBARS
	ACE_MODE_HASKELL
	ACE_MODE_HASKELL_CABAL
	ACE_MODE_HAXE
	ACE_MODE_HJSON
	ACE_MODE_HTML
	ACE_MODE_HTML_ELIXIR
	ACE_MODE_HTML_RUBY
	ACE_MODE_INI
	ACE_MODE_IO
	ACE_MODE_JACK
	ACE_MODE_JADE
	ACE_MODE_JAVA
	ACE_MODE_JAVASCRIPT
	ACE_MODE_JSON
	ACE_MODE_JSONIQ
	ACE_MODE_JSP
	ACE_MODE_JSSM
	ACE_MODE_JSX
	ACE_MODE_JULIA
	ACE_MODE_KOTLIN
	ACE_MODE_LATEX
	ACE_MODE_LESS
	ACE_MODE_LIQUID
	ACE_MODE_LISP
	ACE_MODE_LIVESCRIPT
	ACE_MODE_LOGIQL
	ACE_MODE_LSL
	ACE_MODE_LUA
	ACE_MODE_LUAPAGE
	ACE_MODE_LUCENE
	ACE_MODE_MAKEFILE
	ACE_MODE_MARKDOWN
	ACE_MODE_MASK
	ACE_MODE_MATLAB
	ACE_MODE_MAZE
	ACE_MODE_MEL
	ACE_MODE_MIXAL
	ACE_MODE_MUSHCODE
	ACE_MODE_MYSQL
	ACE_MODE_NIX
	ACE_MODE_NSIS
	ACE_MODE_OBJECTIVE_C
	ACE_MODE_OCAML
	ACE_MODE_PASCAL
	ACE_MODE_PERL
	ACE_MODE_PGSQL
	ACE_MODE_PHP
	ACE_MODE_PIG
	ACE_MODE_POWERSHELL
	ACE_MODE_ACE_MODE_PRAAT
	ACE_MODE_PROLOG
	ACE_MODE_PROPERTIES
	ACE_MODE_PROTOBUF
	ACE_MODE_PYTHON
	ACE_MODE_R
	ACE_MODE_RAZOR
	ACE_MODE_RDOC
	ACE_MODE_RED
	ACE_MODE_RHTML
	ACE_MODE_RST
	ACE_MODE_RUBY
	ACE_MODE_RUST
	ACE_MODE_SASS
	ACE_MODE_SCAD
	ACE_MODE_SCALA
	ACE_MODE_SCHEME
	ACE_MODE_SCSS
	ACE_MODE_SH
	ACE_MODE_SJS
	ACE_MODE_SMARTY
	ACE_MODE_SNIPPETS
	ACE_MODE_SOY_TEMPLATE
	ACE_MODE_SPACE
	ACE_MODE_SQL
	ACE_MODE_SQLSERVER
	ACE_MODE_STYLUS
	ACE_MODE_SVG
	ACE_MODE_SWIFT
	ACE_MODE_TCL
	ACE_MODE_TEX
	ACE_MODE_TEXT
	ACE_MODE_TEXTILE
	ACE_MODE_TOML
	ACE_MODE_TSX
	ACE_MODE_TWIG
	ACE_MODE_TYPESCRIPT
	ACE_MODE_VALA
	ACE_MODE_VBSCRIPT
	ACE_MODE_VELOCITY
	ACE_MODE_VERILOG
	ACE_MODE_VHDL
	ACE_MODE_WOLLOK
	ACE_MODE_XML
	ACE_MODE_XQUERY
	ACE_MODE_YAML
	ACE_MODE_DJANGO
)

type AceMode int

func (el AceMode) String() string {
	return aceModes[el]
}

var aceModes = [...]string{
	"ace/mode/abap",
	"ace/mode/abc",
	"ace/mode/actionscript",
	"ace/mode/ada",
	"ace/mode/apache_conf",
	"ace/mode/asciidoc",
	"ace/mode/asl-ASL",
	"ace/mode/assembly_x86",
	"ace/mode/autohotkey",
	"ace/mode/batchfile",
	"ace/mode/bro",
	"ace/mode/c_cpp",
	"ace/mode/c9search",
	"ace/mode/cirru",
	"ace/mode/clojure",
	"ace/mode/cobol",
	"ace/mode/coffee",
	"ace/mode/coldfusion",
	"ace/mode/csharp",
	"ace/mode/csound_document",
	"ace/mode/csound_orchestra",
	"ace/mode/csound_score",
	"ace/mode/css",
	"ace/mode/curly",
	"ace/mode/d",
	"ace/mode/dart",
	"ace/mode/diff",
	"ace/mode/dockerfile",
	"ace/mode/dot",
	"ace/mode/drools",
	"ace/mode/edifact",
	"ace/mode/eiffel",
	"ace/mode/ejs",
	"ace/mode/elixir",
	"ace/mode/elm",
	"ace/mode/erlang",
	"ace/mode/forth",
	"ace/mode/fortran",
	"ace/mode/ftl",
	"ace/mode/gcode",
	"ace/mode/gherkin",
	"ace/mode/gitignore",
	"ace/mode/glsl",
	"ace/mode/gobstones",
	"ace/mode/golang",
	"ace/mode/graphqlschema",
	"ace/mode/groovy",
	"ace/mode/haml",
	"ace/mode/handlebars",
	"ace/mode/haskell",
	"ace/mode/haskell_cabal",
	"ace/mode/haxe",
	"ace/mode/hjson",
	"ace/mode/html",
	"ace/mode/html_elixir",
	"ace/mode/html_ruby",
	"ace/mode/ini",
	"ace/mode/io",
	"ace/mode/jack",
	"ace/mode/jade",
	"ace/mode/java",
	"ace/mode/javascript",
	"ace/mode/json",
	"ace/mode/jsoniq",
	"ace/mode/jsp",
	"ace/mode/jssm",
	"ace/mode/jsx",
	"ace/mode/julia",
	"ace/mode/kotlin",
	"ace/mode/latex",
	"ace/mode/less",
	"ace/mode/liquid",
	"ace/mode/lisp",
	"ace/mode/livescript",
	"ace/mode/logiql",
	"ace/mode/lsl",
	"ace/mode/lua",
	"ace/mode/luapage",
	"ace/mode/lucene",
	"ace/mode/makefile",
	"ace/mode/markdown",
	"ace/mode/mask",
	"ace/mode/matlab",
	"ace/mode/maze",
	"ace/mode/mel",
	"ace/mode/mixal",
	"ace/mode/mushcode",
	"ace/mode/mysql",
	"ace/mode/nix",
	"ace/mode/nsis",
	"ace/mode/objectivec",
	"ace/mode/ocaml",
	"ace/mode/pascal",
	"ace/mode/perl",
	"ace/mode/pgsql",
	"ace/mode/php",
	"ace/mode/pig",
	"ace/mode/powershell",
	"ace/mode/praat",
	"ace/mode/prolog",
	"ace/mode/properties",
	"ace/mode/protobuf",
	"ace/mode/python",
	"ace/mode/r",
	"ace/mode/razor",
	"ace/mode/rdoc",
	"ace/mode/red",
	"ace/mode/rhtml",
	"ace/mode/rst",
	"ace/mode/ruby",
	"ace/mode/rust",
	"ace/mode/sass",
	"ace/mode/scad",
	"ace/mode/scala",
	"ace/mode/scheme",
	"ace/mode/scss",
	"ace/mode/sh",
	"ace/mode/sjs",
	"ace/mode/smarty",
	"ace/mode/snippets",
	"ace/mode/soy_template",
	"ace/mode/space",
	"ace/mode/sql",
	"ace/mode/sqlserver",
	"ace/mode/stylus",
	"ace/mode/svg",
	"ace/mode/swift",
	"ace/mode/tcl",
	"ace/mode/tex",
	"ace/mode/text",
	"ace/mode/textile",
	"ace/mode/toml",
	"ace/mode/tsx",
	"ace/mode/twig",
	"ace/mode/typescript",
	"ace/mode/vala",
	"ace/mode/vbscript",
	"ace/mode/velocity",
	"ace/mode/verilog",
	"ace/mode/vhdl",
	"ace/mode/wollok",
	"ace/mode/xml",
	"ace/mode/xquery",
	"ace/mode/yaml",
	"ace/mode/django",
}
